# Generated by Django 2.2.6 on 2019-10-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_profe', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('area_de_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=60)),
                ('admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_prestamo', models.DateTimeField()),
                ('devuelto', models.BooleanField()),
                ('area_de_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_profe', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('NV', 'Nuevo'), ('BN', 'Bueno'), ('ML', 'Malo'), ('RT', 'Roto')], default='', max_length=1)),
                ('caracteristicas', models.TextField()),
                ('observaciones', models.TextField()),
                ('conteiner_de_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.Container')),
            ],
        ),
    ]
