# Generated by Django 2.2.6 on 2019-12-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_profe', models.CharField(blank=True, max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('area_de_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.Area')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_profe', models.CharField(blank=True, max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('N', 'Nuevo'), ('B', 'Bueno'), ('M', 'Malo'), ('R', 'Roto')], default='', max_length=1)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_entrada', models.DateField(blank=True, default='12/05/19', null=True)),
                ('container_de_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.Container')),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
            },
        ),
    ]
