# Generated by Django 2.2.6 on 2019-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Container', 'verbose_name_plural': 'Containers'},
        ),
        migrations.AlterModelOptions(
            name='objeto',
            options={'verbose_name': 'Objeto', 'verbose_name_plural': 'Objetos'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'Prestamo', 'verbose_name_plural': 'Prestamos'},
        ),
        migrations.AlterField(
            model_name='objeto',
            name='estado',
            field=models.CharField(choices=[('N', 'Nuevo'), ('B', 'Bueno'), ('M', 'Malo'), ('R', 'Roto')], default='', max_length=1),
        ),
    ]
