# Generated by Django 2.2.6 on 2019-11-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_auto_20191108_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objeto',
            old_name='conteiner_de_origen',
            new_name='container_de_origen',
        ),
    ]
