# Generated by Django 2.2.6 on 2019-11-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_auto_20191108_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='objeto',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.Objeto'),
        ),
    ]
