# Generated by Django 2.2.6 on 2019-11-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_prestamo_objeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='ID_profe',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='ID_profe',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
