# Generated by Django 2.2.6 on 2019-11-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_auto_20191128_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='fecha_entrada',
            field=models.DateField(blank=True, default='11/29/19', null=True),
        ),
    ]
