# Generated by Django 2.2.6 on 2019-11-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_auto_20191129_1136'),
        ('inventory_app', '0006_auto_20191129_1145'),
    ]

    operations = [
    ]
