# Generated by Django 2.2.6 on 2019-11-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0007_merge_20191129_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trasladar',
        ),
    ]
