# Generated by Django 2.2.6 on 2019-11-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0007_merge_20191129_1344'),
        ('inventory_app', '0008_delete_trasladar'),
    ]

    operations = [
    ]
