# Generated by Django 2.2.6 on 2019-12-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0009_merge_20191129_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='fecha_entrada',
            field=models.DateField(blank=True, default='12/02/19', null=True),
        ),
    ]
