# Generated by Django 2.2.6 on 2019-12-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0010_auto_20191201_2203'),
        ('inventory_app', '0010_auto_20191201_1926'),
    ]

    operations = [
    ]
