# Generated by Django 2.2.6 on 2019-12-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0010_auto_20191202_1136'),
        ('inventory_app', '0011_merge_20191201_2236'),
    ]

    operations = [
    ]
