# Generated by Django 2.2.6 on 2019-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0012_merge_20191202_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='fecha_entrada',
            field=models.DateField(blank=True, default='12/05/19', null=True),
        ),
    ]
