# Generated by Django 2.2.6 on 2019-12-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0013_auto_20191205_1216'),
        ('inventory_app', '0013_auto_20191205_1209'),
    ]

    operations = [
    ]
